POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "New Product",
    "price": 29.99
}


GET http://localhost:3000/products

GET http://localhost:3000/products/1

PATCH http://localhost:3000/products/1

Content-Type: application/json

{
    "name": "Updated Product Name",
    "price": 39.99
}

DELETE http://localhost:3000/products/1


POST http://localhost:3000/stock-inputs

Content-Type: application/json

{
    "product_id": 1,
    "quantity": 10,
    "date": "2025-10-15"
}